/*
 * 이 파일의 내용만 수정하면 화면의 콘텐츠가 바뀝니다.
 * 이미지가 없을 때는 image 값을 빈 문자열("")로 두세요.
 */
export const ARCHIVE_DATA = {
  site: {
    lastUpdated: "2026.09.28",
    submitUrl: "https://open.kakao.com/o/gceOSMIi",
  },

items: [
  {
    id: "kimjungmoon-aloe-cure-cooling-sunstick-23g",
    name: "김정문알로에 큐어 쿨링 선스틱 23g",
    category: "선케어",
    image: "https://image.oliveyoung.co.kr/cfimages/cf-goods/uploads/images/thumbnails/10/0000/0016/A00000016270026ko.jpg?l=ko",
    shop: "올리브영",
    price: "",
    url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162700&utm_source=google&utm_medium=shopping_search&utm_campaign=onpro_emnet_googlepmax_health_25_0101_1231&utm_term=&_CAD=google_pmax_health&gad_source=1&gad_campaignid=19855538117&gbraid=0AAAAADKpDR5lSbO5coXqWIlBfVudoVWHe&gclid=CjwKCAjw1vXTBhB-EiwAEKr_k9IOgRwS3C-KW1wlHgw2L21OVuaMY4vOGDRg5iSsj_PGusm8LWR3hhoCo_kQAvD_BwE",
    review:
      "휴대하면서 덧바르기 쉬운 23g 선스틱 타입. 제품명에 쿨링 기능이 명시되어 있어 야외 페스티벌처럼 햇빛과 더위에 오래 노출되는 날 간편한 선케어용으로 활용하기 좋다.",
    points: ["23g 선스틱", "쿨링 타입", "휴대·덧바르기 간편"],
    date: "2026.08.14",
  },
  {
    id: "trillion-utility-belt-multi-cargo-bermuda-shorts-beige",
    name: "유틸리티 벨트 멀티 카고 버뮤다 쇼츠_베이지",
    category: "하의",
    image: "https://thetrillion.co.kr/web/product/big/202507/56609a828a211d7e428a592dd93aed8e.jpg",
    shop: "트릴리온",
    price: "37,900원",
    url: "https://musinsa.onelink.me/PvkC/h03j86vg",
    review:
      "트릴리온 특유의 스트릿 무드가 느껴지는 버뮤다 쇼츠. 벨트 디테일과 멀티 카고 포켓이 포인트라 락페처럼 소지품을 자주 챙겨야 하는 날 활용도가 높다.",
    points: ["멀티 카고 포켓", "벨트 디테일", "버뮤다 핏"],
    date: "2026.08.14",
  },
],

  restaurants: [
    {
      id: "gwang-an-mok-gwangan-busan",
      festival: "",
      venue: "부산 수영구 광안리",
      name: "광안목 광안점",
      category: "한식 · 숙성 돼지고기",
      image: "",
      description: "부산 수영구 광안리에 있는 돼지고기 전문점. 드라이에이징한 목살과 삼겹살, 특수부위를 중심으로 판매한다.",
      menus: ["건조숙성 안목살", "건조숙성 특삼겹", "광안목 뚜껑살", "치즈듬뿍 김치볶음밥", "냉제육 비빔국수"],
      url: "https://map.naver.com/p/entry/place/1401176849",
      date: "2026.09.28",
    },
    {
      id: "yongkangjie-gwangan-main-busan",
      festival: "",
      venue: "부산 수영구 광안리",
      name: "융캉찌에 광안본점",
      category: "중식 · 대만요리",
      image: "",
      description: "부산 수영구 광안리의 대만요리 전문점. 우육탕면과 탄탄면, 마라곱창탕면, 마파두부덮밥 등을 판매한다.",
      menus: ["우육탕면", "탄탄면", "마라곱창탕면", "마파두부덮밥", "가지튀김"],
      url: "https://naver.me/FNlJcsb5",
      date: "2026.09.28",
    },
    {
      id: "daeseong-galchi-jjigae-gijang-busan",
      festival: "",
      venue: "부산 기장군",
      name: "대성갈치찌개구이",
      category: "한식 · 갈치·멸치요리",
      image: "",
      description: "부산 기장군 대변리에 있는 갈치·멸치요리 전문점. 갈치찌개와 갈치구이, 멸치회, 멸치찌개를 판매한다.",
      menus: ["갈치찌개", "갈치구이", "멸치회", "멸치찌개"],
      url: "https://naver.me/5B1vwfPJ",
      date: "2026.09.28",
    },
    {
      id: "wonjo-jipbul-gomjangeo-gijang-oegajip-busan",
      festival: "",
      venue: "부산 기장군",
      name: "원조짚불곰장어 기장외가집",
      category: "한식 · 곰장어",
      image: "",
      description: "부산 기장군 공수마을의 곰장어 전문점. 짚불곰장어를 중심으로 양념곰장어와 바다장어구이, 식사 메뉴를 판매한다.",
      menus: ["짚불곰장어", "양념곰장어", "바다장어구이", "성게미역국", "장어탕"],
      url: "",
      date: "2026.09.28",
    },
    {
      id: "dongbu-hoetjip-gijang-busan",
      festival: "",
      venue: "부산 기장군 일광읍",
      name: "동부횟집",
      category: "회·해산물 · 붕장어",
      image: "",
      description: "부산 기장군 일광읍 칠암리에 있는 붕장어 전문 횟집. 붕장어회와 붕장어구이, 매운탕 등을 판매한다.",
      menus: ["붕장어회", "붕장어구이", "매운탕"],
      url: "",
      date: "2026.09.28",
    },
    {
      id: "kkeomeok-dongne-gijang-busan",
      festival: "",
      venue: "부산 기장군 일광읍",
      name: "꺼먹동네",
      category: "회·해산물 · 붕장어",
      image: "",
      description: "부산 기장군 일광읍 칠암리에 있는 붕장어·회 전문점. 붕장어회와 장어구이, 모둠회 등을 판매한다.",
      menus: ["붕장어회", "장어구이", "모둠회", "마리고기", "우럭구이"],
      url: "",
      date: "2026.09.28",
    },
    {
      id: "choryang-1941-busan",
      festival: "",
      venue: "부산 동구 초량동",
      name: "초량1941",
      category: "카페 · 우유전문",
      image: "",
      description: "부산 동구 초량동 이바구길에 있는 카페. 1941년경 지어진 가옥을 개조했으며 다양한 우유 음료를 주력으로 판매한다.",
      menus: ["바닐라우유", "커피바닐라우유", "생강우유", "홍차우유", "말차우유"],
      url: "https://map.naver.com/p/search/%EC%B4%88%EB%9F%891941/place/286366050?c=15.00,0,0,0,dh&placePath=%3Fbk_query%253D%2525EC%2525B4%252588%2525EB%25259F%2525891941%2526entry%253Dbmp",
      date: "2026.09.28",
    },
    {
      id: "sinbalwon-choryang-busan",
      festival: "",
      venue: "부산 동구 초량동",
      name: "신발원",
      category: "중식 · 중국만두",
      image: "",
      description: "부산 동구 초량동 차이나타운의 중국만두 전문점. 고기만두와 군만두를 중심으로 새우만두와 마라만두 등을 판매한다.",
      menus: ["고기만두", "군만두", "새우만두", "부추당면만두", "마라만두"],
      url: "https://map.naver.com/p/entry/place/11833745?c=15.00,0,0,0,dh&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281117%26locale%3Dko%26svcName%3Dmap_pcv5",
      date: "2026.09.28",
    },
    {
      id: "oporto-choryang-busan",
      festival: "",
      venue: "부산 동구 초량동",
      name: "오포르투",
      category: "베이커리 · 포르투갈식 디저트",
      image: "",
      description: "부산 동구 초량동에 있는 포르투갈·브라질 스타일 베이커리 카페. 포르투갈식 에그타르트와 곶감발효종 빵, 커피 메뉴를 판매한다.",
      menus: ["포르투갈 에그타르트", "곶감발효종 트러플 치즈", "꽈뜨로 치즈 곶감발효종 빵", "마자그란", "포르투갈식 라떼 갈렁"],
      url: "https://map.naver.com/p/entry/place/1680147021?c=15.00,0,0,0,dh&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281117%26locale%3Dko%26svcName%3Dmap_pcv5",
      date: "2026.09.28",
    },
    {
      id: "geumyong-mandu-gupo-busan",
      festival: "",
      venue: "부산 북구 구포동",
      name: "금용만두",
      category: "중식 · 중국만두",
      image: "",
      description: "부산 북구 구포동에 있는 산둥식 중국만두 전문점. 1960년부터 운영해왔으며 찐만두와 군만두가 대표 메뉴다.",
      menus: ["찐만두", "군만두"],
      url: "https://map.naver.com/p/entry/place/11722896?c=15.00,0,0,0,dh&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281116%26locale%3Dko%26svcName%3Dmap_pcv5",
      date: "2026.09.28",
    },
    {
      id: "daegwolan-jip-sasang-busan",
      festival: "",
      venue: "부산 사상구",
      name: "대궐안집",
      category: "한식 · 한우·갈비",
      image: "",
      description: "부산 사상구 괘법동에 있는 한우·갈비 전문점. 갈비탕과 한우 생갈비, 양념갈비, 안창살 등을 판매한다.",
      menus: ["갈비탕", "한우 생갈비", "한우 양념갈비", "한우 안창살", "한우 갈비살"],
      url: "https://map.naver.com/p/entry/place/11830757?c=15.00,0,0,0,dh&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281115%26locale%3Dko%26svcName%3Dmap_pcv5",
      date: "2026.09.28",
    },
    {
      id: "haemul-wangchang-kalguksu-deokpo-busan",
      festival: "",
      venue: "부산 사상구 덕포동",
      name: "해물왕창칼국수",
      category: "한식 · 해물칼국수",
      image: "",
      description: "부산 사상구 덕포동에 있는 해물칼국수 전문점. 해물칼국수와 육전밀면, 해물왕창파전 등을 판매한다.",
      menus: ["해물칼국수", "육전밀면", "육전비빔밀면", "해물왕창파전", "수제왕만두"],
      url: "https://map.naver.com/p/search/%EB%8D%95%ED%8F%AC%20%ED%95%B4%EB%AC%BC%EC%99%95%EC%B0%BD/place/36192662?c=15.00,0,0,0,dh&placePath=%2Fhome%3Fbk_query%3D%EB%8D%95%ED%8F%AC%20%ED%95%B4%EB%AC%BC%EC%99%95%EC%B0%BD%26entry%3Dbmp%26from%3Dmap%26fromPanelNum%3D2%26timestamp%3D202609281115%26locale%3Dko%26svcName%3Dmap_pcv5%26searchText%3D%EB%8D%95%ED%8F%AC%20%ED%95%B4%EB%AC%BC%EC%99%95%EC%B0%BD",
      date: "2026.09.28",
    },
    {
      id: "hapcheon-ilryu-dwaejigukbap-sasang-busan",
      festival: "",
      venue: "부산 사상구",
      name: "합천일류돼지국밥",
      category: "한식 · 돼지국밥",
      image: "",
      description: "부산 사상구 광장로에 있는 돼지국밥 전문점. 고기국밥과 돼지우동, 섞어국밥, 순대국밥, 수육백반 등을 판매한다.",
      menus: ["고기국밥", "돼지우동", "섞어국밥", "순대국밥", "수육백반"],
      url: "https://map.naver.com/p/entry/place/20299805?c=15.00,0,0,0,dh&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281115%26locale%3Dko%26svcName%3Dmap_pcv5",
      date: "2026.09.28",
    },
    {
      id: "choi-ppyeodagu-haejangguk-sasang-busan",
      festival: "",
      venue: "부산 사상구",
      name: "최뼈다구해장국",
      category: "한식 · 해장국·감자탕",
      image: "",
      description: "부산 사상구 괘법동의 해장국·감자탕 전문점. 뼈해장국과 감자탕을 중심으로 왕갈비탕 등 식사 메뉴를 판매한다.",
      menus: ["해장국", "감자탕 소", "감자탕 중", "감자탕 대", "왕갈비탕"],
      url: "https://map.naver.com/p/entry/place/12861579?c=15.00,0,0,0,dh&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281114%26locale%3Dko%26svcName%3Dmap_pcv5",
      date: "2026.09.28",
    },
    {
      id: "halmae-jaecheopguk-sasang-busan",
      festival: "",
      venue: "부산 사상구",
      name: "할매재첩국",
      category: "한식 · 재첩국",
      image: "",
      description: "부산 사상구 삼락동 재첩골목의 재첩국 전문점. 재첩국과 재첩회, 재첩찜을 판매하며 재첩국 주문 시 밥과 고등어조림 등 반찬이 함께 제공된다.",
      menus: ["재첩국", "재첩회", "재첩찜"],
      url: "https://map.naver.com/p/entry/place/11600631?lng=128.9862105&lat=35.1932712&placePath=%2Fhome%3Ffrom%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202609281114%26locale%3Dko%26svcName%3Dmap_pcv5&entry=plt&searchType=place&c=15.00,0,0,0,dh",
      date: "2026.09.28",
    },
    {
      id: "sindong-flower-crab-iksan",
      festival: "",
      venue: "익산",
      name: "신동꽃게장",
      category: "한식 · 게장",
      image: "https://cdn.udanax.org/place/thumnails/1552872.webp",
      description: "익산 신동에 있는 게장 전문점. 꽃게장백반으로 간장게장과 양념게장, 알탕을 함께 판매한다.",
      menus: ["꽃게장백반", "양념게장", "간장게장", "알탕"],
      url: "https://naver.me/xVBhkqRK",
      date: "2026.08.14",
    },
    {
      id: "dongseone-octopus-main-iksan",
      festival: "",
      venue: "익산",
      name: "동서네낙지 본점",
      category: "한식 · 낙지요리",
      image: "https://d12zq4w4guyljn.cloudfront.net/300_300_20260706012034_photo1_26b73923e7e1.webp",
      description: "익산 인북로46길에 있는 낙지요리 전문점. 낙지볶음과 낙지소곱창볶음을 중심으로 사리를 곁들여 먹는 메뉴를 판매한다.",
      menus: ["낙지볶음", "낙지소곱창볶음", "대패사리(우삼겹)", "낙지사리", "우동사리"],
      url: "https://naver.me/FoENe6uK",
      date: "2026.08.14",
    },
    {
      id: "mermil-jinmijip-main-jeonju",
      festival: "",
      venue: "전주",
      name: "메르밀진미집 본점",
      category: "한식 · 메밀소바",
      image: "https://d12zq4w4guyljn.cloudfront.net/300_300_20260803104538720_photo_f72cb57d8172.webp",
      description: "전주 완산구 전주천동로에 있는 메밀소바 전문점. 3대에 걸쳐 운영해 온 본점으로 소바와 메밀 콩국수, 돈까스 메뉴를 판매한다.",
      menus: ["메밀소바", "땡초소바", "메밀 콩국수", "등심돈까스", "치즈돈까스"],
      url: "https://naver.me/xk1nSZci",
      date: "2026.08.14",
    },
    {
      id: "pnb-pungnyeon-bakery-main-jeonju",
      festival: "",
      venue: "전주",
      name: "PNB 풍년제과 본점",
      category: "베이커리 · 초코파이",
      image: "https://pnb1951.cafe24.com/web/pnb2020/store/PNB_bonjum_1.png",
      description: "전주 완산구 팔달로에 있는 PNB 풍년제과 본점. 수제 초코파이와 붓세, 센베류를 판매하는 베이커리다.",
      menus: ["PNB 오리지널초코파이", "PNB 화이트초코파이", "콘붓세", "땅콩센베", "깨센베"],
      url: "https://naver.me/xf5AihEc",
      date: "2026.08.14",
    },
    {
      id: "cheonghakdong-perilla-jeonju",
      festival: "",
      venue: "전주",
      name: "청학동들깨요리",
      category: "한식 · 들깨요리",
      image: "https://d12zq4w4guyljn.cloudfront.net/300_300_20251117010857_photo1_R0cOVCZJNhBq.webp",
      description: "전주 중화산동의 들깨요리 전문점. 고소한 들깨 육수를 활용한 삼계탕과 갈비탕, 옹심이 메뉴가 중심이라 든든한 식사나 보양식으로 들르기 좋은 곳.",
      menus: ["들깨삼계탕", "들깨옹심이", "들깨소갈비전골", "들깨갈비탕", "들깨갈비옹심이"],
      url: "https://naver.me/FHOwpmwh",
      date: "2026.08.14",
    },
    {
      id: "dajung-hoega-main-jeonju",
      festival: "",
      venue: "전주",
      name: "다정회가 본점",
      category: "일식 · 연어",
      image: "https://d12zq4w4guyljn.cloudfront.net/750_750_20240810024214_photo2_f519baca3ed3.webp",
      description: "전주 중화산동에 있는 연어 전문점. 연어회와 연어초밥을 중심으로 사케동, 연어스테이크 등 다양한 연어 메뉴를 즐길 수 있어 공연 전후 식사 장소로 보기 좋은 곳.",
      menus: ["연어회", "연어초밥", "사케동", "연어스테이크", "연어샐러드"],
      url: "https://naver.me/5Ifa79Xx",
      date: "2026.08.14",
    },
    {
      id: "namno-galbi-main-jeonju",
      festival: "",
      venue: "전주",
      name: "남노갈비 본점",
      category: "한식 · 물갈비",
      image: "https://d12zq4w4guyljn.cloudfront.net/750_750_20260105115426_photo2_KvOfSuNnt6JM.webp",
      description: "전주 한옥마을 인근에서 남노물갈비를 대표 메뉴로 내는 갈비전골 전문점.",
      menus: ["남노물갈비", "떡갈비", "당면사리", "라면사리", "비빔채"],
      url: "https://naver.me/GII0e2hF",
      date: "2026.08.14",
    },
  ],

  rooms: [
    { name: "26 JUMF 공유방", description: "", url: "https://open.kakao.com/o/g5DgYeJi", note: "", active: true },
    { name: "운동하는 여자들 🏃🏃‍♀️🏃‍♂️", description: "작은 일에도 부둥부둥 해드립니다", url: "https://open.kakao.com/o/g8OMTZvh", note: "복복복🫳🫳🫳", active: true },
    { name: "캠핑 혼자가는 여자들", description: "락가여 파생 캠핑방", url: "https://open.kakao.com/o/gMYasvIi", note: "입장 시 닉네임 / 지역 / 선호캠핑종류 입력", active: true },
  ],

  shares: [
    {
      type: "택시",
      title: "그풀캠 광주송정역 → 짱뚱어해수욕장 카풀",
      date: "2026.09.04",
      time: "오후 3시 이후",
      from: "광주송정역",
      to: "짱뚱어해수욕장",
      cost: "1인당 약 25,000원",
      duration: "",
      status: "모집중",
      host: "",
      note: "카카오벤티 이용. 3인 모집(현재 2인 확정 / 총 5인). 귀가는 협의 후 결정.",
      url: "https://open.kakao.com/o/s6nQoALi",
      posted: "2026.09.02",
    },
    {
      type: "택시",
      title: "11:38 전주역 → 전주대 택시팟",
      date: "2026.08.15",
      time: "11:38 전주역 도착 후",
      from: "전주역",
      to: "전주대학교",
      cost: "택시 약 10,000원",
      duration: "약 20분",
      status: "마감",
      host: "붕어빵",
      note: "서울에서 전주 방면 KTX 중 11:38 전주역 도착 열차 이용자 대상. 셔틀은 약 40~50분 소요되어 택시 동승자를 모집합니다.",
      url: "#",
      posted: "2026.08.14",
    },
  ],

  transfers: [
    {
      type: "티켓",
      event: "[양수] 부산락페스티벌 3일권 구해요",
      date: "2026.10.02~10.04",
      quantity: "1매",
      price: "정가",
      status: "거래중",
      method: "양수 희망 · 작성자: 발빠진쥐 · 작성자 태그 또는 오픈프로필 문의 · 양도해 주시면 대선 칵테일 제공",
      url: "",
      posted: "2026.09.13",
    },
  ],
};
