/*
 * 이 파일의 내용만 수정하면 화면의 콘텐츠가 바뀝니다.
 * 이미지가 없을 때는 image 값을 빈 문자열("")로 두세요.
 */
export const ARCHIVE_DATA = {
  site: {
    lastUpdated: "2026.08.14",
    submitUrl: "https://open.kakao.com/o/gceOSMIi",
  },

items: [
  {
    id: "kimjungmoon-aloe-cure-cooling-sunstick-23g",
    name: "김정문알로에 큐어 쿨링 선스틱 23g",
    category: "선케어",
    image: "",
    shop: "올리브영",
    price: "",
    url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162700&utm_source=google&utm_medium=shopping_search&utm_campaign=onpro_emnet_googlepmax_health_25_0101_1231&utm_term=&_CAD=google_pmax_health&gad_source=1&gad_campaignid=19855538117&gbraid=0AAAAADKpDR5lSbO5coXqWIlBfVudoVWHe&gclid=CjwKCAjw1vXTBhB-EiwAEKr_k9IOgRwS3C-KW1wlHgw2L21OVuaMY4vOGDRg5iSsj_PGusm8LWR3hhoCo_kQAvD_BwE",
    review:
      "휴대하면서 덧바르기 쉬운 23g 선스틱 타입. 제품명에 쿨링 기능이 명시되어 있어 야외 페스티벌처럼 햇빛과 더위에 오래 노출되는 날 간편한 선케어용으로 활용하기 좋다.",
    points: ["23g 선스틱", "쿨링 타입", "휴대·덧바르기 간편"],
    date: "2026.08.14",
  },
  {
    id: "trillion-utility-belt-multi-cargo-bermuda-shorts-beige",
    name: "유틸리티 벨트 멀티 카고 버뮤다 쇼츠_베이지",
    category: "하의",
    image: "https://thetrillion.co.kr/web/product/big/202507/56609a828a211d7e428a592dd93aed8e.jpg",
    shop: "트릴리온",
    price: "37,900원",
    url: "https://musinsa.onelink.me/PvkC/h03j86vg",
    review:
      "트릴리온 특유의 스트릿 무드가 느껴지는 버뮤다 쇼츠. 벨트 디테일과 멀티 카고 포켓이 포인트라 락페처럼 소지품을 자주 챙겨야 하는 날 활용도가 높다.",
    points: ["멀티 카고 포켓", "벨트 디테일", "버뮤다 핏"],
    date: "2026.08.14",
  },
],

  restaurants: [
    {
      id: "sindong-flower-crab-iksan",
      festival: "",
      venue: "익산",
      name: "신동꽃게장",
      category: "한식 · 게장",
      image: "",
      description: "익산 신동에 있는 게장 전문점. 꽃게장백반으로 간장게장과 양념게장, 알탕을 함께 판매한다.",
      menus: ["꽃게장백반", "양념게장", "간장게장", "알탕"],
      url: "https://naver.me/xVBhkqRK",
      date: "2026.08.14",
    },
    {
      id: "dongseone-octopus-main-iksan",
      festival: "",
      venue: "익산",
      name: "동서네낙지 본점",
      category: "한식 · 낙지요리",
      image: "",
      description: "익산 인북로46길에 있는 낙지요리 전문점. 낙지볶음과 낙지소곱창볶음을 중심으로 사리를 곁들여 먹는 메뉴를 판매한다.",
      menus: ["낙지볶음", "낙지소곱창볶음", "대패사리(우삼겹)", "낙지사리", "우동사리"],
      url: "https://naver.me/FoENe6uK",
      date: "2026.08.14",
    },
    {
      id: "mermil-jinmijip-main-jeonju",
      festival: "",
      venue: "전주",
      name: "메르밀진미집 본점",
      category: "한식 · 메밀소바",
      image: "",
      description: "전주 완산구 전주천동로에 있는 메밀소바 전문점. 3대에 걸쳐 운영해 온 본점으로 소바와 메밀 콩국수, 돈까스 메뉴를 판매한다.",
      menus: ["메밀소바", "땡초소바", "메밀 콩국수", "등심돈까스", "치즈돈까스"],
      url: "https://naver.me/xk1nSZci",
      date: "2026.08.14",
    },
    {
      id: "pnb-pungnyeon-bakery-main-jeonju",
      festival: "",
      venue: "전주",
      name: "PNB 풍년제과 본점",
      category: "베이커리 · 초코파이",
      image: "https://pnb1951.cafe24.com/web/pnb2020/store/PNB_bonjum_1.png",
      description: "전주 완산구 팔달로에 있는 PNB 풍년제과 본점. 수제 초코파이와 붓세, 센베류를 판매하는 베이커리다.",
      menus: ["PNB 오리지널초코파이", "PNB 화이트초코파이", "콘붓세", "땅콩센베", "깨센베"],
      url: "https://naver.me/xf5AihEc",
      date: "2026.08.14",
    },
    {
      id: "cheonghakdong-perilla-jeonju",
      festival: "",
      venue: "전주",
      name: "청학동들깨요리",
      category: "한식 · 들깨요리",
      image: "https://d12zq4w4guyljn.cloudfront.net/300_300_20251117010857_photo1_R0cOVCZJNhBq.webp",
      description: "전주 중화산동의 들깨요리 전문점. 고소한 들깨 육수를 활용한 삼계탕과 갈비탕, 옹심이 메뉴가 중심이라 든든한 식사나 보양식으로 들르기 좋은 곳.",
      menus: ["들깨삼계탕", "들깨옹심이", "들깨소갈비전골", "들깨갈비탕", "들깨갈비옹심이"],
      url: "https://naver.me/FHOwpmwh",
      date: "2026.08.14",
    },
    {
      id: "dajung-hoega-main-jeonju",
      festival: "",
      venue: "전주",
      name: "다정회가 본점",
      category: "일식 · 연어",
      image: "https://d12zq4w4guyljn.cloudfront.net/750_750_20240810024214_photo2_f519baca3ed3.webp",
      description: "전주 중화산동에 있는 연어 전문점. 연어회와 연어초밥을 중심으로 사케동, 연어스테이크 등 다양한 연어 메뉴를 즐길 수 있어 공연 전후 식사 장소로 보기 좋은 곳.",
      menus: ["연어회", "연어초밥", "사케동", "연어스테이크", "연어샐러드"],
      url: "https://naver.me/5Ifa79Xx",
      date: "2026.08.14",
    },
    {
      id: "namno-galbi-main-jeonju",
      festival: "",
      venue: "전주",
      name: "남노갈비 본점",
      category: "한식 · 물갈비",
      image: "https://d12zq4w4guyljn.cloudfront.net/750_750_20260105115426_photo2_KvOfSuNnt6JM.webp",
      description: "전주 한옥마을 인근에서 남노물갈비를 대표 메뉴로 내는 갈비전골 전문점.",
      menus: ["남노물갈비", "떡갈비", "당면사리", "라면사리", "비빔채"],
      url: "https://naver.me/GII0e2hF",
      date: "2026.08.14",
    },
  ],

  rooms: [
    { name: "운동하는 여자들 🏃🏃‍♀️🏃‍♂️", description: "작은 일에도 부둥부둥 해드립니다", url: "https://open.kakao.com/o/g8OMTZvh", note: "복복복🫳🫳🫳", active: true },
    { name: "캠핑 혼자가는 여자들", description: "락가여 파생 캠핑방", url: "https://open.kakao.com/o/gMYasvIi", note: "입장 시 닉네임 / 지역 / 선호캠핑종류 입력", active: true },
  ],

  transfers: [],
};